# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da89b0aabe3496f606cb46caa4910afd148a8d4f8f54ac9cb46a75c9c042d201b3ac744aaeb03332e1b74049f90c166f973d11315b350b864e7ffed6480dfeb3

test:
  secret_key_base: ff8ed07b11fd2d437c59b733888001186bcf95136f8e7a7126a8e1b50f53aed68bae8e8ce63863331af15a9e74ca806f9f348cbbc69ced0c0cab6203ba2f591d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
